### ISSUE TITLE
pa-banner Doesn't Work with Bootstrap Carousels

### ISSUE THREAD

**Issue by Justintime50** [Justintime50/Pineapple#7]
In the docs we state that the `.pa-banner` class will work on Bootstrap Carousels when in fact they don't. To get carousels full-screen like a normal static banner image, we need to add the following CSS:

```css
.carousel-item {
  background-position: center;
  height: 100%;
  background-position: center;
  -webkit-background-size: cover;
  /* For WebKit */
  -moz-background-size: cover;
  /* Mozilla */
  -o-background-size: cover;
  /* Opera */
  background-size: cover;
  /* Generic */
  background-attachment: fixed;
}

.carousel-inner {
  height: 100%;
}
```

Basically, we need to apply the same CSS we would to the static banner image as we do to the carousel containers. We should either add a new class for carousels to accomplish full-screen switching images or we should extend the already existing `.pa-banner` class to work on static images in addition to the carousel.
